name = "sapho-task-score-api"
main = "src/index.js"
compatibility_date = "2026-05-31"

[[d1_databases]]
binding = "DB"
database_name = "sapho-task-score-db"
database_id = "3d508763-c817-453f-bdb2-64120f5bf280"
